# Generated by Django 5.0.6 on 2024-07-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_checkoutaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutaddress',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
    ]
